version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
  
      - JWT_SECRET=mysecret
      - OPENAI_API_KEY=openai_api_key
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - '3306:3306'
